.TH FLWRITE 1 "" "" "Copy / delete files on Flex disk image"
.SH NAME
flwrite \- Copy files to a flex disk image
.SH SYNOPSIS
.B flwrite
[\fI\-h\fP]
.br
.B flwrite
[\fI\-d\fP] [\fI\-f\fP] [\fI\-v\fP] file [file]... disk-image-name
.PP
.B fldel
[\fI\-f\fP] [\fI\-v\fP] file [file]... disk-image-name
.SH DESCRIPTION
.PP
Flwrite copy or delete files to an existing flex disk image.
.PP
Fldel is a shortcut for
.B flwrite
\fI\-d\fP.
.PP
Both commands return 0 if all files can be copied or deleted, 1 if some files were not treated,
and 2 if nothing can be done.
.PP
If a unusual geometry is found,
.B flwrite
will quit with a warning message.
.BR Flan (1)
can be used to understand what's going on.
The option
.I \-f
forces the update if one consider there is no error.
.PP
However, if the free sector chained list is not clean,
.B flwrite
allways exit.
One must run
.B flan
.I \-r
to correct this before running the command again.
.PP
Files are copied with no conversion except when they start with '#RAND##FLEX#'.
In this case, the file is reconstructed and flagged as a random access file.
.SH OPTIONS
.TP
.B \-d
Delete named file(s) from the disk image, don't copy anything.
.TP
.B \-f
Force: don't quit if disk image geometry is unusual.
.TP
.B \-h
Help: print a short usage summary and exit.
.TP
.B \-v
Verbose: give some hints about what's done and the files added or deleted.
.SH COPYRIGHT
.PP
\fBFlwrite\fR is Copyright \(co 2022 Michel J. Wurtz.
.br
\fBFlwrite\fR is open source software, released under the terms of the GNU General
Public License as published by the Free Software Foundation; either version 2,
or any later version.
.SH SEE ALSO
.PP
fflex(1), flan(1), fldump(1), flunpack(1), flpack(1).
